trigger:
- main

pool:
  name: Default

steps:

- checkout: self

- task: Maven@4
  displayName: 'Build Spring PetClinic'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

- script: docker build -t petclinic:latest .
  displayName: 'Build Docker Image'

- script: kubectl apply -f deployment.yaml
  displayName: 'Deploy Deployment'

- script: kubectl apply -f service.yaml
  displayName: 'Deploy Service'